allowBuilds:
  esbuild: true
  unrs-resolver: true

autoInstallPeers: true

enablePrePostScripts: true

minimumReleaseAge: 2880 # 2 days

minimumReleaseAgeExclude:
  - '@webdeveric/utils@0.76.0'

strictPeerDependencies: true
