name: Node.js CI

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: Continuous Integration
    strategy:
      fail-fast: true
      matrix:
        node: [20, 22]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'
      - name: Installing dependencies
        run: pnpm install --frozen-lockfile
      - name: Linting
        run: pnpm lint
      - name: Type checking
        run: pnpm typecheck
      - name: Testing
        run: pnpm coverage
      - name: Building
        run: pnpm build
